language: groovy
jdk:
  - oraclejdk8
branches:
  only:
    - feature/travisCiUnitTests
script: .grailsw clean
	&& ./grailsw clean-all
	&& ./grailsw refresh-dependencies
  && ./grailsw "test-app unit:"
  && ./grailsw "war"
