version: '2'

services:

  osm:
    image: iteratec/openspeedmonitor:latest
    container_name: osm_service
    entrypoint: dockerize -wait tcp://osm_mysql:3306 -timeout 240s /entrypoint.sh
    ports:
     - "8080:8080"
    links:
     - osm_mysql
    env_file:
      - .env_osm

  osm_mysql:
    image: mysql
    container_name: osm_mysql
    volumes:
      - osm_mysql_data:/var/lib/mysql
    env_file:
      - .env_osm_mysql

volumes:
  osm_mysql_data:
    driver: local