version: '2'

services:

  osm:
    image: iteratec/openspeedmonitor:latest
    container_name: osm_service
    entrypoint: dockerize -wait tcp://osm_mysql:3306 -timeout 240s /entrypoint.sh
    env_file:
      - .env_osm

  osm_mysql:
    image: mysql
    container_name: osm_mysql
    volumes:
      - osm_mysql_data:/var/lib/mysql
    env_file:
      - .env_osm_mysql

networks:
  default:
    external:
      name: reverse_proxy_net

volumes:
  osm_mysql_data:
    driver: local